import 'package:hive_flutter/hive_flutter.dart';
import 'package:witchy/core/constants/database_keys.dart';
import 'package:witchy/domain/models/period_cycle.dart';
import 'package:witchy/domain/models/daily_log.dart';
import 'package:witchy/domain/models/pregnancy_state.dart';
import 'package:witchy/domain/models/perimenopause_state.dart';

class LocalDatabaseService {
  static final LocalDatabaseService _instance = LocalDatabaseService._internal();
  factory LocalDatabaseService() => _instance;
  LocalDatabaseService._internal();

  Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    Hive.registerAdapter(PeriodCycleAdapter());
    Hive.registerAdapter(DailyLogAdapter());
    Hive.registerAdapter(PregnancyStateAdapter());
    Hive.registerAdapter(PerimenopauseStateAdapter());

    await Hive.openBox<PeriodCycle>(DatabaseKeys.periodCyclesBox);
    await Hive.openBox<DailyLog>(DatabaseKeys.dailyLogsBox);
    await Hive.openBox<PregnancyState>(DatabaseKeys.pregnancyStatesBox);
    await Hive.openBox<PerimenopauseState>(DatabaseKeys.perimenopauseStatesBox);
  }

  Box<PeriodCycle> get periodCyclesBox => Hive.box<PeriodCycle>(DatabaseKeys.periodCyclesBox);
  Box<DailyLog> get dailyLogsBox => Hive.box<DailyLog>(DatabaseKeys.dailyLogsBox);
  Box<PregnancyState> get pregnancyStatesBox => Hive.box<PregnancyState>(DatabaseKeys.pregnancyStatesBox);
  Box<PerimenopauseState> get perimenopauseStatesBox => Hive.box<PerimenopauseState>(DatabaseKeys.perimenopauseStatesBox);

  Box get getBox(String boxName) => Hive.box(boxName);
}
